### ISSUE TITLE
dev-server stops with syntax error

### ISSUE THREAD

**Issue by knherzog** [ioBroker/dev-server#317]
during installation the dev-server throws an exception. After installation the same issue occurs.
This is a fresh download and install. Unfortunately no version information available.

```
knherzog@debian:~$ dev-server watch
/home/knherzog/.npm-global/lib/node_modules/@iobroker/dev-server/node_modules/@iobroker/testing/build/tests/integration/lib/dbConnection.js:161
        await this._objectsClient?.destroy();
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/knherzog/.npm-global/lib/node_modules/@iobroker/dev-server/dist/index.js:31:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

Mod: formatted

**Comment by Apollon77** [comment]
Which nodejs version you use? I assume you need at least Nodejs 14 because you use the iobroker testing lib that only supports nodejs 14+ ...

**Comment by knherzog** [comment]
v12.22.12

I will update immediately and come back.

**Comment by UncleSamSwiss** [comment]
Updated the documentation accordingly

**Comment by Apollon77** [comment]
@UncleSamSwiss In fact it is NOT the dev-server that requires this! The reason for the "error" is that the adapter uses the most current @iobroker/testing in v4 and this is requiring Node.js 14 ... but yes most likely the note still makes sense :-)
