### ISSUE TITLE
Firefox fails to connect after a few changes

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/dev-server#80]
If you run `dev-server watch` and change something on the UI it will update in Browser automagically. In Firefox this already leads to errors in Console:
![dev-server-errors-update](https://user-images.githubusercontent.com/620860/126629722-1909f62d-f6c1-4100-830d-87cdb04b02b1.JPG)

Usually after the third change a reconnect does never happen. The frontend seems to be stuck in some kind of retry loop and never can create a new connection. See image and text log below. 

In the end there is a text log from dev-server console (which is not very talkactive).

If the Browser is in this state you need to either close and restart the browser or dev-server. 

![dev-server-reconnect](https://user-images.githubusercontent.com/620860/126629896-cd42c289-fe30-4414-9124-91bd352bb70f.JPG)

```

██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
index.js:66689:11
Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters index.js:66690:11
Help us to create open source project with reactJS! index.js:66691:11
See you :) index.js:66692:11
[2021-07-20T08:55:50.134Z] Try to connect socket.io.js:59:41
1 index.js:80139:13
Source map error: Error: request failed with status 404
Resource URL: http://localhost:8085/adapter/ico/build/index.js
Source Map URL: /index.js.map
2
[2021-07-20T08:56:07.266Z] ws connection error: CLOSE_GOING_AWAY socket.io.js:61:32
1 index.js:80139:13
[2021-07-20T08:56:07.274Z] Start reconnect 0 socket.io.js:59:41
[2021-07-20T08:56:07.276Z] Try to connect socket.io.js:59:41
Uncaught SyntaxError: missing } after property list
index.js:3430:113note: { opened at line 120, column 3index.js:120:3
Material-UI: the createMuiTheme function was renamed to createTheme.

You should use `import { createTheme } from '@material-ui/core/styles'` index.js:32757:15

██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
index.js:66689:11
Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters index.js:66690:11
Help us to create open source project with reactJS! index.js:66691:11
See you :) index.js:66692:11
[2021-07-20T08:56:08.307Z] Try to connect socket.io.js:59:41
Source map error: Error: request failed with status 404
Resource URL: http://localhost:8085/adapter/ico/build/index.js
Source Map URL: /index.js.map

2 index.js:80139:13
[2021-07-20T08:56:22.416Z] ws connection error: CLOSE_GOING_AWAY socket.io.js:61:32
2 index.js:80139:13
XHRPOSThttp://localhost:8085/browser-sync/socket.io/?EIO=3&transport=polling&t=Nh38M29&sid=7O1UnS9WkElinWaqAAAC
[HTTP/1.1 400 Bad Request 2ms]

[2021-07-20T08:56:22.423Z] Start reconnect 0 socket.io.js:59:41
[2021-07-20T08:56:22.425Z] Try to connect socket.io.js:59:41
Uncaught SyntaxError: missing } after property list
index.js:62757:1422note: { opened at line 120, column 3index.js:120:3
Material-UI: the createMuiTheme function was renamed to createTheme.

You should use `import { createTheme } from '@material-ui/core/styles'` index.js:32757:15

██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
index.js:66689:11
Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters index.js:66690:11
Help us to create open source project with reactJS! index.js:66691:11
See you :) index.js:66692:11
[2021-07-20T08:56:23.555Z] Try to connect socket.io.js:59:41
Source map error: Error: request failed with status 404
Resource URL: http://localhost:8085/adapter/ico/build/index.js
Source Map URL: /index.js.map

[2021-07-20T08:56:26.560Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-07-20T08:56:26.561Z] Start reconnect 0 socket.io.js:59:41
Firefox can’t establish a connection to the server at ws://localhost:8085/?sid=1626771383555&name=ico. socket.io.js:91:21
[2021-07-20T08:56:26.561Z] Try to connect socket.io.js:59:41
The connection to ws://localhost:8085/?sid=1626771383555&name=ico was interrupted while the page was loading. socket.io.js:91:21
[2021-07-20T08:56:26.564Z] Start reconnect 1 socket.io.js:59:41
Firefox can’t establish a connection to the server at ws://localhost:8085/?sid=1626771386562&name=ico. socket.io.js:91:21
[2021-07-20T08:56:26.564Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-07-20T08:56:26.565Z] Reconnect is already running 1 socket.io.js:59:41
The connection to ws://localhost:8085/?sid=1626771386562&name=ico was interrupted while the page was loading. socket.io.js:91:21
[2021-07-20T08:56:26.565Z] Reconnect is already running 1 socket.io.js:59:41
[2021-07-20T08:56:26.565Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-07-20T08:56:26.565Z] Reconnect is already running 1 socket.io.js:59:41
[2021-07-20T08:56:27.573Z] Try to connect socket.io.js:59:41
XHRPOSThttp://localhost:8085/browser-sync/socket.io/?EIO=3&transport=polling&t=Nh38NXG&sid=g39Rn7-QKhejtShHAAAE
[HTTP/1.1 400 Bad Request 5322ms]

[2021-07-20T08:56:30.588Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-07-20T08:56:30.589Z] Start reconnect 2 socket.io.js:59:41
Firefox can’t establish a connection to the server at ws://localhost:8085/?sid=1626771387573&name=ico. socket.io.js:91:21
The connection to ws://localhost:8085/?sid=1626771387573&name=ico was interrupted while the page was loading. socket.io.js:91:21
[2021-07-20T08:56:30.590Z] Reconnect is already running 2 socket.io.js:59:41
[2021-07-20T08:56:30.590Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-07-20T08:56:30.591Z] Reconnect is already running 2 socket.io.js:59:41
[2021-07-20T08:56:32.603Z] Try to connect socket.io.js:59:41
XHRPOSThttp://localhost:8085/browser-sync/socket.io/?EIO=3&transport=polling&t=Nh38OlV&sid=g39Rn7-QKhejtShHAAAE
[HTTP/1.1 400 Bad Request 317ms]

Firefox can’t establish a connection to the server at ws://localhost:8085/browser-sync/socket.io/?EIO=3&transport=websocket&sid=g39Rn7-QKhejtShHAAAE. browser-sync-client.js:10:60395
The connection to ws://localhost:8085/browser-sync/socket.io/?EIO=3&transport=websocket&sid=g39Rn7-QKhejtShHAAAE was interrupted while the page was loading. browser-sync-client.js:10:60395
3 index.js:80139:13
Firefox can’t establish a connection to the server at ws://localhost:8085/browser-sync/socket.io/?EIO=3&transport=websocket&sid=cSDrqlt9TCjCrAS3AAAF. browser-sync-client.js:10:60395
The connection to ws://localhost:8085/browser-sync/socket.io/?EIO=3&transport=websocket&sid=cSDrqlt9TCjCrAS3AAAF was interrupted while the page was loading. browser-sync-client.js:10:60395
[2021-07-20T08:56:49.704Z] ws connection error: CLOSE_GOING_AWAY socket.io.js:61:32
3 index.js:80139:13
[2021-07-20T08:56:49.711Z] Start reconnect 0 socket.io.js:59:41
[2021-07-20T08:56:49.711Z] Try to connect socket.io.js:59:41
[2021-07-20T08:56:52.728Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-07-20T08:56:52.729Z] Start reconnect 1 socket.io.js:59:41
Firefox can’t establish a connection to the server at ws://localhost:8085/?sid=1626771409712&name=ico. socket.io.js:91:21
The connection to ws://localhost:8085/?sid=1626771409712&name=ico was interrupted while the page was loading. socket.io.js:91:21
[2021-07-20T08:56:52.729Z] Reconnect is already running 1 socket.io.js:59:41
[2021-07-20T08:56:52.730Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-07-20T08:56:52.730Z] Reconnect is already running 1 socket.io.js:59:41
[2021-07-20T08:56:53.741Z] Try to connect socket.io.js:59:41
[2021-07-20T08:56:56.755Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-07-20T08:56:56.756Z] Start reconnect 2 socket.io.js:59:41
Firefox can’t establish a connection to the server at ws://localhost:8085/?sid=1626771413741&name=ico. socket.io.js:91:21
The connection to ws://localhost:8085/?sid=1626771413741&name=ico was interrupted while the page was loading. socket.io.js:91:21
[2021-07-20T08:56:56.757Z] Reconnect is already running 2 socket.io.js:59:41
[2021-07-20T08:56:56.757Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-07-20T08:56:56.758Z] Reconnect is already running 2 socket.io.js:59:41
[2021-07-20T08:56:58.765Z] Try to connect socket.io.js:59:41
[2021-07-20T08:57:01.780Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-07-20T08:57:01.782Z] Start reconnect 3 socket.io.js:59:41
Firefox can’t establish a connection to the server at ws://localhost:8085/?sid=1626771418765&name=ico. socket.io.js:91:21
The connection to ws://localhost:8085/?sid=1626771418765&name=ico was interrupted while the page was loading. socket.io.js:91:21
[2021-07-20T08:57:01.782Z] Reconnect is already running 3 socket.io.js:59:41
[2021-07-20T08:57:01.782Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-07-20T08:57:01.782Z] Reconnect is already running 3 socket.io.js:59:41
[2021-07-20T08:57:04.794Z] Try to connect socket.io.js:59:41
[2021-07-20T08:57:07.798Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-07-20T08:57:07.798Z] Start reconnect 4 socket.io.js:59:41
Firefox can’t establish a connection to the server at ws://localhost:8085/?sid=1626771424794&name=ico. socket.io.js:91:21
The connection to ws://localhost:8085/?sid=1626771424794&name=ico was interrupted while the page was loading. socket.io.js:91:21
[2021-07-20T08:57:07.799Z] Reconnect is already running 4 socket.io.js:59:41
[2021-07-20T08:57:07.799Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-07-20T08:57:07.800Z] Reconnect is already running 4 socket.io.js:59:41
[2021-07-20T08:57:11.809Z] Try to connect socket.io.js:59:41
[2021-07-20T08:57:14.817Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-07-20T08:57:14.817Z] Start reconnect 5 socket.io.js:59:41
Firefox can’t establish a connection to the server at ws://localhost:8085/?sid=1626771431809&name=ico. socket.io.js:91:21
The connection to ws://localhost:8085/?sid=1626771431809&name=ico was interrupted while the page was loading. socket.io.js:91:21
[2021-07-20T08:57:14.818Z] Reconnect is already running 5 socket.io.js:59:41
[2021-07-20T08:57:14.819Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-07-20T08:57:14.819Z] Reconnect is already running 5 socket.io.js:59:41
[2021-07-20T08:57:19.824Z] Try to connect socket.io.js:59:41
[2021-07-20T08:57:22.829Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-07-20T08:57:22.830Z] Start reconnect 5 socket.io.js:59:41
Firefox can’t establish a connection to the server at ws://localhost:8085/?sid=1626771439824&name=ico. socket.io.js:91:21
The connection to ws://localhost:8085/?sid=1626771439824&name=ico was interrupted while the page was loading. socket.io.js:91:21
[2021-07-20T08:57:22.831Z] Reconnect is already running 5 socket.io.js:59:41
[2021-07-20T08:57:22.831Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-07-20T08:57:22.831Z] Reconnect is already running 5 socket.io.js:59:41
```
(look for index.js:80139:13 to see output of 1, 2 and 3. That is where the updates were processed).

```
2021-07-20 10:44:30.180  - debug: host.dev-ico-KM Incoming Host message getLogs
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
√  Built in 1.04s.
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
√  Built in 1.14s.
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
√  Built in 657ms.
2021-07-20 10:49:18.054  - debug: host.dev-ico-KM Incoming Host message getInstalled
2021-07-20 10:49:18.076  - debug: host.dev-ico-KM Incoming Host message getRepository
Send diag info: {"uuid":"028e5730-dd03-bfd3-661f-67eae064f8eb","language":"de","country":"","hosts":[{"version":"3.3.14","platform":"Javascript/Node.js","type":"win32"}],"node":"v14.16.0","arch":"x64","adapters":{"admin":{"vers
ion":"5.1.10","platform":"Javascript/Node.js"},"ico":{"version":"0.0.1","platform":"Javascript/Node.js"}},"statesType":"file","objectsType":"file","model":"AMD Ryzen 9 5950X 16-Core Processor            ","cpus":32,"mem":686363
72992,"ostype":"Windows_NT","city":""}
2021-07-20 10:49:20.349  - debug: host.dev-ico-KM Incoming Host message readBaseSettings
[HPM] Client disconnected
```

**Comment by Garfonso** [comment]
Current workaround: Use Chrome. 

To check: Chrome does not run into errors during update. Maybe it will fail after a certain number of errors, too? (Firefox seems to be stuck at Reconnect 5 forever, maybe that can happen in chrome, too?).

**Comment by AlCalzone** [comment]
Can confirm. I can cause the live reload to fail after a few recompilations in Firefox. Chrome seems to be stable.
